Repository agargaro/three.ez, pull requests merged in 2023-11, with the labels that each got.

#45 Added IntersectionUtils
  docs/scripts/utils.ts
  package.json
  src/index.ts
  src/utils/IntersectionUtils.ts
  src/utils/VectorUtils.ts
Labels: enhancement

#46 AssetManager
  src/utils/Asset.ts
Labels: enhancement

#47 Asset - Added Load
  src/utils/Asset.ts
Labels: enhancement

#48 Utils - Added setAllChildrenDragTarget
  src/utils/Utils.ts
Labels: enhancement

#49 Utils - Added computeBoundingSphereChildren and getNodes
  src/utils/Asset.ts
  src/utils/Utils.ts
Labels: enhancement

#50 Asset documentation
  docs/docs/tutorial/advanced/_category_.yml
  docs/docs/tutorial/animation.md
  docs/docs/tutorial/asset-management.md
  docs/docs/tutorial/binding.md
  docs/docs/tutorial/drag-and-drop.md
  docs/docs/tutorial/drag-drop/_category_.yml
  docs/docs/tutorial/drag-drop/todo.md
  docs/docs/tutorial/events/_category_.yml
  docs/docs/tutorial/events/interaction.md
  docs/docs/tutorial/events/misc.md
  docs/docs/tutorial/events/update.md
  docs/docs/tutorial/focus-management.md
  docs/docs/tutorial/focus-management/_category_.yml
  docs/docs/tutorial/focus-management/todo.md
  docs/docs/tutorial/index.md
  docs/docs/tutorial/instancedMesh2.md
  docs/docs/tutorial/migration.md
  docs/docs/tutorial/raycasting.md
  docs/docs/tutorial/resizing.md
  docs/docs/tutorial/tweening.md
  docs/docusaurus.config.js
  docs/src/components/HomepageFeatures/index.tsx
Labels: documentation

#51 Events: Renamed rendererresize to viewportresize
  README.md
  docs/docs/tutorial/events/misc.md
  docs/docs/tutorial/index.md
  docs/src/components/HomepageFeatures/index.tsx
  src/cameras/OrthographicCameraAuto.ts
  src/cameras/PerspectiveCameraAuto.ts
  src/events/Events.ts
  src/events/MiscEventsManager.ts
  src/instancedMesh/EventsDispatcherInstanced.ts
  src/patch/WebGLRenderer.ts
Labels: enhancement

#54 Asset: Fix loadAll undefined config
  src/utils/Asset.ts
Labels: bug

#55 Asset: Error handling
  docs/docs/tutorial/asset-management.md
  src/utils/Asset.ts
Labels: enhancement

#57 Asset: preload refactor parameters
  src/utils/Asset.ts
Labels: enhancement

#58 Tween: Added support to Vector2 and Vector4
  src/index.ts
  src/tweening/Actions.ts
Labels: enhancement

#59 Tween: Fix elapsedTime to return NaN when browser page is inactive
  src/tweening/RunningTween.ts
Labels: bug

#63 Fix Query
  src/utils/Query.ts
Labels: bug
