Repository agargaro/three.ez, pull requests merged in 2024-09, with the labels that each got.

#94 Events: fix mouse events on firefox
  README.md
  package.json
  src/events/RaycasterManager.ts
  src/patch/Material.ts
  src/patch/Object3D.ts
  src/rendering/RenderManager.ts
Labels: bug

#96 Stats: Improve panels
  package.json
  packages/InstancedMesh2/README.md
  src/core/Main.ts
  src/patch/WebGLRenderer.ts
  src/rendering/RenderManager.ts
  src/utils/Stats.ts
Labels: enhancement

#97 docs(Object3D): clarify interceptByRaycaster behavior
  src/patch/Object3D.ts
Labels: documentation
